version: '3.8'

services:
  mysql-db:
    image: mysql:8.0

    environment:
      MYSQL_DATABASE: devsecops_app
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"


    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  spring-app:
    build: .
    container_name: spring-app

    depends_on:
      mysql-db:
        condition: service_healthy

    ports:
      - "8081:8081"

    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/devsecops_app
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
