# ===============================
# SERVER
# ===============================
server.port=8081

# ===============================
# DATABASE (ENV-BASED)
# ===============================
#spring.datasource.url=${SPRING_DATASOURCE_URL}
#spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
#spring.datasource.password=${SPRING_DATASOURCE_PASSWORD} 

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/devsecops_app}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:root123}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# ===============================
# FILE UPLOAD
# ===============================
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB

# ===============================
# CUSTOM PATH
# ===============================
upload.path=uploads/ 